### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by planecore** [benjaminsage/PageView#11]
Currently there's no Mac support (except Catalyst), it'd be great to be able to use iPages on macOS.

**Comment by blsage** [comment]
That's an interesting idea. Let me see what I can do.

**Comment by blsage** [comment]
Just pushed native support for the Mac! Let me know if that fits your needs. Working hard to improve it, but wanted to get something out to you now that it works.

**Comment by planecore** [comment]
Off to a great start! I have only two issues:

- Resizing window doesn't effect iPages
- No page dots showing up

**Comment by blsage** [comment]
Gotcha.

Could you send your code & possibly screenshots for resizing window so I can see your specific issue? I was experiencing this myself by couldn't reproduce it.

Also, the page dots are only available in iOS for some reason. I'll look into finding a way to reproduce the behavior. For now, using a custom `selection:` binding with buttons to move forward and back works. Or you can just use this information to do something like `Text("Page \(currentPage)/4")`

Let me know if you find any more problems!

**Comment by blsage** [comment]
The page dots are now available on mac.

**Comment by planecore** [comment]
Great! Thank you! 🙏🏼
 I’ll check it out later and provide feedback.

**Comment by planecore** [comment]
I get an error: Cannot find 'iPageControl' in scope

**Comment by planecore** [comment]
Also, resizing doesn't work even with this sample code:

```
import SwiftUI
import iPages

struct ExampleApp: App {
    @SceneBuilder var body: some Scene {
        WindowGroup {
            iPages {
                Text("Hello World")
                Text("Hello World")
                Text("Hello World")
                Text("Hello World")
            }
        }
    }
}
```

**Comment by planecore** [comment]
Still waiting... @benjaminsage

**Comment by planecore** [comment]
Any update guys? @benjaminsage @AlexFine
