### ISSUE TITLE
Customised views cannot be passed in iPages Initializer

### ISSUE THREAD

**Issue by neptunezxn** [benjaminsage/PageView#4]
I'm trying out iPages however I encountered the following issue.

It's a very basic usage - one master view initializes iPages and two subviews A and B.

**MasterView.swift**
```
import SwiftUI
import iPages

struct MasterView: View {
    @State var currentPage: Int = 0
    var body: some View {
        iPages([SubViewA(), SubViewB()], currentPage: $currentPage)
    }
}
```

**SubViewA.swift**
```
import SwiftUI

struct SubViewA: View {
    var body: some View {
        Text("this is subview A")
    }
}
```

**SubViewB.swift**
```
import SwiftUI

struct SubViewB: View {
    var body: some View {
        Text("this is subview B")
    }
}
```

The above code does not compile with the unhelpful error as follows.
![image](https://user-images.githubusercontent.com/31994715/96713407-72635000-1398-11eb-8176-db78eeedd5c8.png)

**Environment**
XCode: Version 12.0.1
macOS: Catalina 10.15.7

Please can anyone suggest if I'm doing anything incorrect or there is a bug somewhere in the library? Thanks in advance!

**Comment by blsage** [comment]
I know what's going on. Will push a fix in a bit.

**Comment by blsage** [comment]
Fixed bug, and updating the documentation now. One thing to be aware of, `iPages` now takes a trailing view builder closure of ordered views as pages, just like `VStack` or `ZStack`:
```swift
import SwiftUI
import iPages

struct ContentView: View {
    @State var currentPage: Int = 0

    var body: some View {
        iPages(currentPage: $currentPage) {
            Color.red
            Text("iPages")
        }
    }
}
```

Let me know if you have any questions or find any more bugs.
