### ISSUE TITLE
Can't use custom Views

### ISSUE THREAD

**Issue by callaghanjames** [benjaminsage/PageView#5]
Hello!

Absolutely love the look of this but I've been struggling to get it working with custom views. I keep getting an error saying **Cannot convert value of type _someCustomView_ to closure result type '[UIViewController]'**

Is there something I'm doing wrong?

Here's a screenshot of my code too:
![Screenshot 2020-10-22 at 12 16 30](https://user-images.githubusercontent.com/32676227/96864806-e701c180-1460-11eb-8b8f-b07cf1e43cb7.png)

Thanks in advance!

**Comment by blsage** [comment]
Hey, I think I know the issue. I think it's breaking when you use only 1 page (not a very common use case so I probably forgot to test it). Try it with multiple pages, and let me know if it works. I'll also get working on this bug.

**Comment by blsage** [comment]
Got it. Should work with just 1 page now. Let me know

**Comment by callaghanjames** [comment]
Great, working perfectly now! Thanks so much!
