### ISSUE TITLE
After putting view inside iPage {}, change state will not update the child view

### ISSUE THREAD

**Issue by DechengMa** [benjaminsage/PageView#7]
Hi, This is a nice package and quite easy to use.

Just encounter the issue: after putting my custom view inside an iPage view, all the child view lost the ability to react to state changes:

Example:
```
struct SetUpView: View {
    @State var foo: String = "Hello"

    var body: some View {
        ZStack {
            Text("\(foo)")

            Button("Button") {
                foo = "123"
            }
        }
        .ignoresSafeArea(.all)
    }
}
```
After putting this view inside iPage, when the button clicked, the text won't get changed.
```
            iPages {
                SetUpView()
            }
            .ignoresSafeArea(.all)
```
and it works normal when put outside the iPage block.

Any solution?

**Comment by blsage** [comment]
Hey Decheng,

This appears to only be a problem when you have just 1 page in the view, which I assume you were only doing for testing purposes. I'll spend some time trying to track this down, but for now, just add more pages to the view, and let me know if you continue to have issues.

Ben

**Comment by blsage** [comment]
Fixed :)
