### ISSUE TITLE
Change state in parent view of iPage will trigger unwanted animation

### ISSUE THREAD

**Issue by DechengMa** [benjaminsage/PageView#8]
Hi there, thanks for the quick fix yesterday now it works like charm!

Just encounter another issue, when I change the state of iPage parents view, iPage will trigger an unwanted animation. 
#### Example code:
```
struct TabViewParentView: View {
    @State var selectedIndex: Int = 0
    @State var tabViewIsHidden: Bool = false

    var body: some View {
        ZStack {
            iPages(selection: $selectedIndex) {
                ProfileView()
                SecondView()
                ThirdView()
            }
            .hideDots(true)

            VStack {
                Button {
                    tabViewIsHidden = !tabViewIsHidden
                } label: {
                    Text("HELLO THERE!")
                }

                Spacer()

                Text("TEXT")
                    .foregroundColor(.white)
                    .opacity(tabViewIsHidden ? 0 : 1)
            }
        }
    }

}
```

When the button pressed and @State tabViewIsHidden was changed, the iPage will scroll to the same page with animation: 
#### Demo:
![Screen Recording 2020-10-27 at 1 30 29 pm](https://user-images.githubusercontent.com/30752103/97249810-b5219e00-1858-11eb-9813-e0c23296a763.gif)

I wonder if it is possible to prevent this? This is needed for making my custom tab view control, I was making an auto dismissed tab view control, but when I change the state, this unwanted animation was triggered.

**Comment by blsage** [comment]
Ah, this is quite interesting. Please give me a minute to look into it.

**Comment by blsage** [comment]
Should be fixed! I also added a `.animated(_:)` modifier which can allow you to disable animation altogether. 😀
