### ISSUE TITLE
Selection binding brakes swiping

### ISSUE THREAD

**Issue by planecore** [benjaminsage/PageView#9]
That's what happens when I try to scroll between several pages with selection binding:

Video:
https://streamable.com/aiva4p

Code:

```
struct TestView: View {
    @State var selectedIdx = 0

    var body: some View {
        iPages(selection: $selectedIdx) {
            Color.red
            Color.blue
            Color.yellow
        }
        .onChange(of: selectedIdx) { value in
            print("INDEX: \(value)")
         }
    }
}
```

**Comment by blsage** [comment]
Very interesting. I was able to reproduce the error. Quick question, is this also only happening for you when you use the `.onChange` receiver? I will look into this.

**Comment by planecore** [comment]
Any updates?

**Comment by blsage** [comment]
Honestly thanks for this. Made me realize there was a flaw in `iPages` that was affecting a lot of places. I restructured things a bit and I'm not getting this bug anymore. It should be fixed.
